'use client';

import { useState, useEffect, useRef } from 'react';
import { ArtStyle, resolveAutoStyle, ART_STYLE_INFO } from './CodeEditor';
import { CodeMetrics } from '@/lib/analyzer';
import { RefreshCw, Download, Sparkles, Wand2, Info, X } from 'lucide-react';
import { GoogleGenAI } from "@google/genai";
import ArtBot from './ArtBot';
import { useLocale } from '@/context/LocaleContext';

interface AiGeneratorProps {
    metrics: CodeMetrics;
    artStyle: ArtStyle;
    aiProvider: 'openai' | 'gemini';
    setAiProvider: (provider: 'openai' | 'gemini') => void;
    autoGenerateOnLoad: boolean;
}

export default function AiGenerator({
    metrics,
    artStyle,
    aiProvider,
    setAiProvider,
    autoGenerateOnLoad
}: AiGeneratorProps) {
    const { t, language: locale } = useLocale();
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
    const [docentText, setDocentText] = useState<string | null>(null);
    const [docentError, setDocentError] = useState<string | null>(null);
    const [isGeneratingDocent, setIsGeneratingDocent] = useState(false);
    const [isConfirmingStyle, setIsConfirmingStyle] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const hasOpenAI = !!process.env.NEXT_PUBLIC_OPENAI_KEY;
    const hasGemini = !!process.env.NEXT_PUBLIC_GEMINI_KEY;

    const downloadImage = () => {
        if (!generatedImageUrl) return;
        const link = document.createElement('a');
        link.href = generatedImageUrl;
        link.download = `code2art-${Date.now()}.png`;
        link.click();
    };

    // Guard to prevent double-firing from useEffect + button click
    const hasAutoGenerated = useRef(false);

    // Resolve auto style based on metrics — used throughout prompt generation
    const resolvedStyle = artStyle === 'auto' ? resolveAutoStyle(metrics) : artStyle;
    const resolvedStyleInfo = ART_STYLE_INFO[resolvedStyle];

    const styleNames: Record<string, string> = {
        kandinsky: locale === 'ko' ? '바실리 칸딘스키(추상미술)' : 'Wassily Kandinsky (Abstract)',
        vangogh: locale === 'ko' ? '빈센트 반 고흐(후기인상주의)' : 'Vincent van Gogh (Post-Impressionism)',
        monet: locale === 'ko' ? '클로드 모네(인상주의)' : 'Claude Monet (Impressionism)',
        dali: locale === 'ko' ? '살바도르 달리(초현실주의)' : 'Salvador Dalí (Surrealism)',
        basquiat: locale === 'ko' ? '장 미셸 바스키아(신표현주의)' : 'Jean-Michel Basquiat (Neo-Expressionism)'
    };

    const styleDescriptions: Record<string, string> = {
        kandinsky: `Wassily Kandinsky Abstract style: a musical composition of pure abstraction. Floating circles, sharp triangles, and intersecting lines that create a rhythmic sense of movement. Geometric forms scattered across a vast, ethereal background with a focus on 'inner necessity'. Bold primary colors vibrate like musical notes. The composition is an orchestra of points, lines, and planes interacting in an non-objective, spiritual space.`,
        vangogh: `Vincent van Gogh Post-Impressionist style: thick, heavily impastoed, swirling and spiraling brushstrokes that dynamically fill the entire canvas with kinetic energy. Deep ultramarine and cobalt blues boldly contrasted against burning cadmium yellows and warm ochres. Every mark is a passionate, directional, tactile gesture. The sky and forms vibrate and rotate with inner life.`,
        monet: `Claude Monet Impressionist style: soft, loose, flickering dabs and feathery strokes of color that dissolve hard edges into shimmering light. The palette is luminous — rose, lavender, powder blue, golden yellow, and sage green — all bleeding into each other at the boundaries. The surface feels like a reflection on gently rippling water, atmospheric and dreamlike, full of warmth and natural light.`,
        dali: `Salvador Dalí Surrealist style: hyper-realistic, academically precise oil-painting technique applied to a dreamscape that defies spatial logic. Forms melt, stretch, and morph impossibly. A vast, barren desert-golden landscape forms the backdrop with deep theatrical shadows. Elements float and defy gravity. Despite the impossible content, every detail is rendered with photographic exactitude.`,
        basquiat: `Jean-Michel Basquiat Neo-Expressionist style: raw, energetic, graffiti-influenced painting with boldly scrawled text fragments, expressive crown motifs, bold gestural marks and primitive symbols all layered together. The composition is deliberately chaotic but rhythmically alive. Pure, clashing primary colors burst against dark backgrounds. The mark-making is urgent, spontaneous, and urban — like a wall covered in expressive street art.`
    };

    const getImagePrompt = () => {
        const { complexity: comp, cohesion: coh, consistency: cons, coupling: coup, depth, readability, sentiment, paradigm } = metrics;

        // --- Style-Specific Descriptors ---
        const getDescriptors = () => {
            const getLvl5 = (v: number) => v > 0.8 ? 4 : v > 0.6 ? 3 : v > 0.4 ? 2 : v > 0.2 ? 1 : 0;
            const getLvl3 = (v: number) => v > 0.66 ? 2 : v > 0.33 ? 1 : 0;

            switch (resolvedStyle) {
                case 'kandinsky':
                    return {
                        complexity: [
                            "a singular spiritual point, representing the fundamental essence of form",
                            "a sparse, melodic layout with a few primary shapes floating in open space",
                            "a balanced abstract composition with dynamic tension between geometric clusters",
                            "an intricate rhythmic arrangement of multiple geometric layers and intersecting paths",
                            "a dense, symphonic explosion of overlapping floating geometric symbols, an orchestra of points and arcs"
                        ][getLvl5(comp)],
                        cohesion: [
                            "fully dispersed energy, with points and lines vibrating in independent isolation",
                            "a loose rhythmic cluster suggesting a subtle shared gravitational pull",
                            "converging toward a powerful magnetic core of heavy circular forms"
                        ][getLvl3(coh)],
                        consistency: [
                            "a wild, improvisational clash of dissonant, vibrating colors and irregular forms",
                            "a balanced interaction of complementary hues and varied geometric weights",
                            "a strict, spiritual harmonic palette of pure primary chords and disciplined lines"
                        ][getLvl3(cons)],
                        coupling: [
                            "isolated geometric islands floating in a vast void without visual contact",
                            "elements subtly connected by proximity and invisible harmonic corridors",
                            "shapes tightly interlocked and tethered by a complex web of thin black lines"
                        ][getLvl3(coup)],
                        depth: [
                            "a flat, non-objective interaction of pure surface planes",
                            "subtle layered overlaps creating a sense of shallow pictorial space",
                            "an infinite spiritual void with multiple receding layers of translucent circles"
                        ][getLvl3(depth)],
                        marks: [
                            "tiny, fractured geometric ciphers and staccato mark-making",
                            "rhythmic, controlled dots and precisely measured linear dashes",
                            "sharp, thin-to-thick confident rhythmic lines and perfectly defined perimeters"
                        ][getLvl3(readability)],
                        atmosphere: [
                            "a cool, intellectual atmosphere with somber, introspective blue tones",
                            "a neutral, clear space of objective observation and pure light",
                            "radiating a warm, golden spiritual glow and optimistic energy"
                        ][getLvl3(sentiment)],
                        paradigm: paradigm === 'oop' ? "anchored by monumental, static block-like structures" : "built from dynamic, sweeping arcs and continuous data-stream curves"
                    };
                case 'vangogh':
                    return {
                        complexity: [
                            "sparse, quiet strokes on a raw base, representing total mental clarity",
                            "mostly calm with long, serene horizontal strokes and occasional subtle dabs",
                            "balanced energy, with confident patches of color and steady brushwork rhythm",
                            "rhythmic, flowing rivers of paint, creating constant movement and energetic growth",
                            "a violent, ecstatic explosion of swirling impasto, every millimeter vibrating with restless dashes"
                        ][getLvl5(comp)],
                        cohesion: [
                            "fragmented energy spread across the canvas in independent eddies",
                            "a gentle central pull organizing the brushwork into a unified flow",
                            "an immense gravitational vortex pulling all strokes into a tight, spiraling sun"
                        ][getLvl3(coh)],
                        consistency: [
                            "a turbulent clash of unpredictable, high-contrast emotional hues",
                            "a rich, varied palette of organic greens and warm ochres",
                            "a disciplined, vibrating harmony of deep cyprus blues and radiant sunflower yellows"
                        ][getLvl3(cons)],
                        coupling: [
                            "distinct patches of energy coexisting with clear physical separation",
                            "brushstrokes overlapping at the edges in a loose, organic weave",
                            "heavy impasto threads woven together in an unbreakable, textured knot"
                        ][getLvl3(coup)],
                        depth: [
                            "thick, tactile surface tension that rejects background space",
                            "gentle receding hills and layered sky creating moderate depth",
                            "powerful receding spatial tunnels created by extreme directional perspective"
                        ][getLvl3(depth)],
                        marks: [
                            "short, agitated, staccato marks applied with nervous energy",
                            "standard directional dashes showing steady movement",
                            "long, confident, flowing directional strokes with mature, grand gesture"
                        ][getLvl3(readability)],
                        atmosphere: [
                            "somber and brooding, with heavy shadows and a world-weary air",
                            "a calm, midday light with direct, honest observation",
                            "bathed in a luminous, hopeful morning light with a sense of divine presence"
                        ][getLvl3(sentiment)],
                        paradigm: paradigm === 'oop' ? "framed by heavy, upright vertical cypress-like monuments" : "a continuous flow of liquid energy, like a winding field of wheat"
                    };
                case 'monet':
                    return {
                        complexity: [
                            "an ethereal, almost abstract mist of a single morning hue, quiet and minimalist",
                            "a soft, hazy dawn landscape with gentle washes of light and subtle dabs",
                            "a balanced impressionist view with rhythmic color patches and flickering light",
                            "an intricate garden landscape of overlapping lily pads and complex textures",
                            "a shimmering, hyper-dense surface vibrating with ten thousand tiny dabs of pure light"
                        ][getLvl5(comp)],
                        cohesion: [
                            "fully diffused light spread evenly across the misty pond with no focal point",
                            "a gentle cluster of lilies providing a soft anchoring rhythm",
                            "a radiant central core where all light converges into a single glowing reflection"
                        ][getLvl3(coh)],
                        consistency: [
                            "a surprising variety of light-flickering accents that challenge the harmony",
                            "a balanced interplay of warm and cool reflections",
                            "a perfectly unified, harmonious wash of lavender, rose, and soft sage"
                        ][getLvl3(cons)],
                        coupling: [
                            "soft, isolated clusters of color floating in a vast, misty void",
                            "forms gently touching and sharing common reflected colors",
                            "forms bleeding into each other at the boundaries, completely inseparable"
                        ][getLvl3(coup)],
                        depth: [
                            "a flat, decorative surface of water reflections and floating petals",
                            "a soft sense of recession through overlapping aquatic forms",
                            "ethereal atmospheric perspective with multiple receding layers of mist"
                        ][getLvl3(depth)],
                        marks: [
                            "tiny, flickering points of pure pigment that blur the vision",
                            "medium-length dabs and horizontal strokes typical of water lilies",
                            "soft, feathery, long sweeps of light color and gentle washes"
                        ][getLvl3(readability)],
                        atmosphere: [
                            "cool, introspective twilight with muted, melancholic shadows",
                            "the clear, steady light of a bright spring morning",
                            "warm, optimistic afternoon sun diffused through a golden haze"
                        ][getLvl3(sentiment)],
                        paradigm: paradigm === 'oop' ? "structured by a stable, solid bridge-like horizontal axis" : "a flowing, formless stream of light and data without rigid anchors"
                    };
                case 'dali':
                    return {
                        complexity: [
                            "a pure, flat infinite horizon under a single suspended floating orb, extremely sparse",
                            "a vast, empty desert void with a single strange, isolated melting artifact",
                            "a balanced dreamscape with several melting objects and sharp, long shadows",
                            "a dense surrealist construction of warped perspectives and multiple melting icons",
                            "a nightmarish, hyper-detailed landscape of melting towers and impossible mechanisms"
                        ][getLvl5(comp)],
                        cohesion: [
                            "multiple objects floating in complete logical isolation in a vast vacuum",
                            "objects starting to orbit around a central strange occurrence",
                            "a surreal convergence where all melting objects fuse into a single central monument"
                        ][getLvl3(coh)],
                        consistency: [
                            "an eerie palette of clashing neon hues and unnatural, toxic shadows",
                            "hyper-real colors that feel slightly off-balance and strange",
                            "a controlled sequence of desert-earth tones and crystal-clear sky blues"
                        ][getLvl3(cons)],
                        coupling: [
                            "sharp, self-contained objects casting long, independent shadows",
                            "objects tethered by thin, impossible strings or stretching parts",
                            "melting forms physically merging and collapsing into one another"
                        ][getLvl3(coup)],
                        depth: [
                            "a theatrical flat stage set with a curtain-like foreground",
                            "wide desert plains with several layers of receding visual depth",
                            "infinite receding horizon line with logically impossible, deep spatial tunnels"
                        ][getLvl3(depth)],
                        marks: [
                            "fractured, microscopic details that reveal hidden coded symbols",
                            "sharp, standard oil-painting rendering with realistic texture",
                            "ultra-sharp, academic brushwork with photographic exactitude"
                        ][getLvl3(readability)],
                        atmosphere: [
                            "a somber, twilight atmosphere of impending decay and deep anxiety",
                            "a mid-day dream, bright but unsettlingly quiet",
                            "crisp, ultra-clear morning light with a sense of profound awakening"
                        ][getLvl3(sentiment)],
                        paradigm: paradigm === 'oop' ? "monumental, architectural structures rising like pillars of power" : "liquid, melting data-flows that reject any solid structural foundation"
                    };
                case 'basquiat':
                    return {
                        complexity: [
                            "one single, bold, skeletal stroke on a raw background, extremely minimalist",
                            "sparse markings, a single primitive figure on a plain, textured wall",
                            "a balanced expressionist wall of raw marks and primitive urban icons",
                            "intricate street-art layering of skeletal figures, scribbles, and text fragments",
                            "explosive urban chaos, hyper-dense layers of spray-paint, oil-sticks, and symbols"
                        ][getLvl5(comp)],
                        cohesion: [
                            "fully dispersed graffiti-energy with no discernible center or hierarchy",
                            "a strong central axis with scrawled arrows pointing inward",
                            "commanded by a massive, central primitive crown icon that dominates the space"
                        ][getLvl3(coh)],
                        consistency: [
                            "a wild, chaotic riot of clashing spray-paint, charcoal, and neon streaks",
                            "a gritty, urban palette of greys, browns, and street textures",
                            "a disciplined clash of 3-4 raw primary tones against a black ground"
                        ][getLvl3(cons)],
                        coupling: [
                            "raw, separate symbols and icons floating on a bare wall background",
                            "scribbles and text fragments that overlap and interact organically",
                            "layers of overpainting and crossed-out text covering every inch of the figure"
                        ][getLvl3(coup)],
                        depth: [
                            "a primary, flat, immediate 2D wall surface with raw markings",
                            "suggested depth through layering and scratching away paint",
                            "heavy collaged layers of surfaces, showing historical depth through accumulation"
                        ][getLvl3(depth)],
                        marks: [
                            "tiny, nervous scribbles and scratched-away, skeletal marks",
                            "bold spray-paint drips and grease-crayon scratches",
                            "aggressive, confident, and long gestural lines of oil-stick"
                        ][getLvl3(readability)],
                        atmosphere: [
                            "brooding, political anger with dark, somber tones and skeletal anxieties",
                            "urgent, raw street communication with high energy",
                            "raw, celebratory urban energy — loud, proud, and unapologetic"
                        ][getLvl3(sentiment)],
                        paradigm: paradigm === 'oop' ? "heavily framed by solid, primitive block-like figures" : "a constant flow of aggressive scrawled text and data-symbols"
                    };
                default:
                    return {
                        complexity: "balanced tension between order and chaos",
                        cohesion: "unified focal point",
                        consistency: "harmonious color distribution",
                        coupling: "moderately connected elements",
                        depth: "subtle layered depth",
                        marks: "confident and expressive marks",
                        atmosphere: "neutral and balanced mood",
                        paradigm: "assembled from fundamental shapes"
                    };
            }
        };

        const d = getDescriptors();

        // Metric-based modifiers that refine the style
        const intensity = comp > 0.7 ? "overwhelmingly intense and dense" : comp < 0.3 ? "minimalist and serene" : "balanced";
        const flow = readability > 0.5 ? "confident and fluid" : "fractured and staccato";

        const prompt = `Create a museum-quality masterpiece in the style of ${styleDescriptions[resolvedStyle]}.
        
Compositional energy: ${intensity}, representing code complexity (${comp.toFixed(2)}).
Core Structure: ${d.complexity}.
Focal Point: ${d.cohesion}, reflecting cohesion (${coh.toFixed(2)}).
Color & Tone: ${d.consistency}, reflecting consistency (${cons.toFixed(2)}).
Atmosphere and Mood: ${d.atmosphere}, reflecting sentiment (${sentiment.toFixed(2)}).
Spatial Feel: ${d.depth}, reflecting depth (${depth.toFixed(2)}).
Connectivity: ${d.coupling}, reflecting coupling (${coup.toFixed(2)}).
Forms and Brushwork: ${d.paradigm}, rendered with ${d.marks}.

Theme: This is a visualization of a computer program's logic. Let the hidden architecture of the code emerge through the ${styleNames[resolvedStyle]} aesthetic.

**CRITICAL INSTRUCTION**: The resulting image MUST be the raw artwork only. DO NOT include any frames, borders, easels, walls, gallery rooms, or surrounding environments. Fill the entire image edge-to-edge with the painting itself. No text in the image.`;

        return prompt;
    };

    const getDocentPrompt = () => {
        const { complexity, cohesion, consistency, coupling, depth, readability, sentiment, paradigm, linesOfCode } = metrics;
        const styleName = styleNames[resolvedStyle];

        // Classification helpers for natural language
        const lvl = (v: number, low: string[], mid: string[], high: string[]) =>
            v > 0.6 ? high[locale === 'ko' ? 0 : 1] : v < 0.35 ? low[locale === 'ko' ? 0 : 1] : mid[locale === 'ko' ? 0 : 1];

        const complexityLvl = lvl(complexity, ['간결하고 정돈된', 'concise and organized'], ['균형 잡힌', 'balanced'], ['복잡하고 역동적인', 'complex and dynamic']);
        const cohesionLvl = lvl(cohesion, ['분산된', 'dispersed'], ['느슨하게 연결된', 'loosely connected'], ['강하게 응집된', 'strongly cohesive']);
        const consistencyLvl = lvl(consistency, ['대비가 강하고 불규칙한', 'high-contrast and irregular'], ['적당히 다채로운', 'moderately colorful'], ['절제되고 조화로운', 'restrained and harmonious']);
        const couplingLvl = lvl(coupling, ['독립적이고 분리된', 'independent and decoupled'], ['부분적으로 연결된', 'partially connected'], ['촘촘하게 얽힌', 'tightly coupled']);
        const depthLvl = depth > 0.5
            ? (locale === 'ko' ? '입체적이고 깊이감 있는' : 'dimensional and deep')
            : (locale === 'ko' ? '평면적이고 고요한' : 'flat and serene');
        const readLvl = readability > 0.5
            ? (locale === 'ko' ? '유려하고 서술적인' : 'fluent and descriptive')
            : (locale === 'ko' ? '짧고 압축적인' : 'dense and concise');
        const sentLvl = sentiment > 0.65
            ? (locale === 'ko' ? '따뜻하고 밝은' : 'warm and bright')
            : sentiment < 0.35
                ? (locale === 'ko' ? '차분하고 성찰적인' : 'calm and reflective')
                : (locale === 'ko' ? '중립적이고 절제된' : 'neutral and restrained');

        const paradigmLvl = paradigm === 'oop'
            ? (locale === 'ko' ? '객체지향적(OOP)' : 'Object-Oriented (OOP)')
            : paradigm === 'fp'
                ? (locale === 'ko' ? '함수형(FP)' : 'Functional (FP)')
                : (locale === 'ko' ? '절차적(Procedural)' : 'Procedural');

        const roleRequest = locale === 'ko'
            ? `당신은 세계적인 현대 미술관의 수석 도슨트입니다. 다음 정보를 바탕으로 관람객에게 들려주는 해설을 4~6문장 한국어로 작성하세요.`
            : `You are a world-class chief curator at a modern art museum. Based on the following information, write a commentary for visitors in 4-6 sentences in English.`;

        return `${roleRequest}

[Artwork Foundation]
Style: ${styleName}
Code DNA: ${linesOfCode} lines, ${paradigmLvl} paradigm.
Structure: ${complexityLvl} complexity, ${cohesionLvl} cohesion, ${consistencyLvl} consistency.
Relationships: ${couplingLvl} coupling, ${depthLvl} logic depth.
Style: ${readLvl} expression, ${sentLvl} emotional tone.

- Do not list raw numbers.
- Explain how code traits manifested as visual elements (color, stroke, composition, etc.).
- Be poetic and analytical.
- Return only the commentary text.`;
    };

    const generateDocent = async () => {
        const openAIKey = process.env.NEXT_PUBLIC_OPENAI_KEY || '';
        const geminiKey = process.env.NEXT_PUBLIC_GEMINI_KEY || '';
        const currentKey = aiProvider === 'openai' ? openAIKey : geminiKey;
        const cleanApiKey = currentKey.trim().replace(/[^\x20-\x7E]/g, '');

        if (!cleanApiKey) return;

        setIsGeneratingDocent(true);
        setDocentError(null);
        try {
            const docentPrompt = getDocentPrompt();

            if (aiProvider === 'openai') {
                const res = await fetch('/api/generate-docent', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ prompt: docentPrompt, apiKey: cleanApiKey })
                });
                const data = await res.json();
                if (data.error) {
                    setDocentError(`OpenAI Docent Error: ${data.error}`);
                } else if (data.choices?.[0]?.message?.content) {
                    setDocentText(data.choices[0].message.content.trim());
                } else {
                    setDocentError("Could not parse docent response.");
                }
            } else if (aiProvider === 'gemini') {
                const ai = new GoogleGenAI({ apiKey: cleanApiKey });
                const response = await ai.models.generateContent({
                    model: "gemini-2.5-flash", // Adjusted to a common model name if 2.5 is not available
                    contents: [{ parts: [{ text: docentPrompt }], role: 'user' }],
                });
                const rawText = response.candidates?.[0]?.content?.parts
                    ?.map((p: any) => p.text || '')
                    ?.join('') ?? '';
                if (rawText.trim()) {
                    setDocentText(rawText.trim());
                } else {
                    setDocentError("Gemini docent response is empty.");
                }
            }
        } catch (e: any) {
            console.error("Docent generation failed:", e);
            setDocentError(`Error generating docent: ${e.message || String(e)}`);
        } finally {
            setIsGeneratingDocent(false);
        }
    };

    const handleGenerate = async () => {
        setError(null);
        const openAIKey = process.env.NEXT_PUBLIC_OPENAI_KEY || '';
        const geminiKey = process.env.NEXT_PUBLIC_GEMINI_KEY || '';
        const currentKey = aiProvider === 'openai' ? openAIKey : geminiKey;

        if (!currentKey) {
            setError(aiProvider === 'openai' ? t('error.openai_key') : t('error.gemini_key'));
            return;
        }

        const cleanApiKey = currentKey.trim().replace(/[^\x20-\x7E]/g, '');

        setIsGenerating(true);
        setIsConfirmingStyle(true);
        setError(null);
        setDocentText(null);

        // Intentional delay for style confirmation phase
        await new Promise(resolve => setTimeout(resolve, 3000));
        setIsConfirmingStyle(false);

        const imagePrompt = getImagePrompt();

        try {
            let imageUrl: string | null = null;

            if (aiProvider === 'openai') {
                const res = await fetch('/api/generate-image', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ prompt: imagePrompt, apiKey: cleanApiKey })
                });

                const data = await res.json();

                if (data.error) {
                    setError(data.error);
                } else if (data.data?.[0]?.url) {
                    imageUrl = data.data[0].url;
                } else {
                    setError("Image generation failed.");
                }
            } else if (aiProvider === 'gemini') {
                const ai = new GoogleGenAI({ apiKey: cleanApiKey });

                const response = await ai.models.generateContent({
                    model: "gemini-3.1-flash-image-preview", // Adjusted to typical preview model
                    contents: [{ text: imagePrompt }],
                });

                if (response.candidates?.[0]?.content?.parts) {
                    for (const part of response.candidates[0].content.parts) {
                        if (part.inlineData) {
                            const base64Data = part.inlineData.data;
                            const mimeType = part.inlineData.mimeType || "image/png";
                            imageUrl = `data:${mimeType};base64,${base64Data}`;
                            break;
                        }
                    }
                    if (!imageUrl) {
                        // Fallback to pollination if Gemini Flash Image is not active
                        imageUrl = `https://pollinations.ai/p/${encodeURIComponent(imagePrompt)}?width=1024&height=1024&seed=${Math.floor(Math.random() * 1000)}&nologo=true`;
                    }
                } else {
                    imageUrl = `https://pollinations.ai/p/${encodeURIComponent(imagePrompt)}?width=1024&height=1024&seed=${Math.floor(Math.random() * 1000)}&nologo=true`;
                }
            }

            if (imageUrl) {
                setGeneratedImageUrl(imageUrl);
                generateDocent();
            }
        } catch (err: any) {
            setError(err.message || "An error occurred during the request.");
        } finally {
            setIsGenerating(false);
        }
    };

    useEffect(() => {
        const hasKey = aiProvider === 'openai'
            ? !!process.env.NEXT_PUBLIC_OPENAI_KEY
            : !!process.env.NEXT_PUBLIC_GEMINI_KEY;

        if (autoGenerateOnLoad && hasKey && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            handleGenerate();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const currentPrompt = getImagePrompt();

    return (
        <div className="w-full max-w-2xl mt-8 p-6 bg-white neo-box border-2 border-secondary">

            {/* Header */}
            <div className="flex items-start justify-between mb-3">
                <div>
                    <h3 className="text-xl font-bold flex items-center gap-2">
                        <Sparkles className="text-secondary" />
                        {t('result.title')}
                    </h3>
                    <p className="text-xs text-gray-400 mt-0.5">
                        {aiProvider === 'openai' ? 'DALL-E 3' : 'Gemini Image'} · {resolvedStyleInfo.label[locale]}
                    </p>
                </div>
                {artStyle === 'auto' && (
                    <div className="flex items-center gap-1.5 px-2.5 py-1 bg-primary/10 border border-primary/20 rounded-full">
                        <Wand2 size={11} className="text-primary" />
                        <span className="text-xs font-bold text-primary">{t('editor.style.auto')}: {resolvedStyleInfo.label[locale]}</span>
                    </div>
                )}
            </div>

            {/* ArtBot animation — visible while loading */}
            {(isGenerating || isGeneratingDocent) && (
                <div className="mb-4">
                    <ArtBot phase={isConfirmingStyle ? 0 : isGeneratingDocent ? 2 : 1} />
                </div>
            )}

            {/* Controls — shown only before generation, hidden while loading */}
            {!generatedImageUrl && !isGenerating && !isGeneratingDocent && (
                <div className="flex flex-col gap-4">
                    <div className="flex flex-col md:flex-row gap-3">
                        <select
                            value={aiProvider}
                            onChange={(e) => setAiProvider(e.target.value as 'openai' | 'gemini')}
                            className="neo-box-sm px-3 py-2 text-sm bg-white flex-grow"
                        >
                            {hasGemini && <option value="gemini">{t('editor.model.gemini')}</option>}
                            {hasOpenAI && <option value="openai">{t('editor.model.openai')}</option>}
                        </select>

                        <button
                            onClick={handleGenerate}
                            disabled={isGenerating}
                            className={`neo-box-sm font-bold px-6 py-2 flex items-center gap-2 transition-all 
                                bg-secondary text-white hover:bg-[#ffafa0]
                                disabled:opacity-50 disabled:cursor-not-allowed`}
                        >
                            {isGenerating ? <RefreshCw className="animate-spin" size={18} /> : <Sparkles size={16} />}
                            {isGenerating ? t('editor.analyzing') : t('editor.analyze')}
                        </button>
                    </div>
                </div>
            )}

            {error && (
                <div className="relative text-red-500 text-sm font-bold p-4 bg-red-50 border-2 border-red-200 rounded-lg mt-4 shadow-sm animate-in fade-in slide-in-from-top-2 duration-300">
                    <button
                        onClick={() => setError(null)}
                        className="absolute top-2 right-2 text-red-300 hover:text-red-500 transition-colors"
                    >
                        <X size={16} />
                    </button>
                    <div className="flex items-start gap-3">
                        <span className="text-lg">⚠️</span>
                        <div className="flex flex-col gap-1">
                            <p className="leading-tight">{error}</p>
                            <p className="text-[10px] font-normal text-red-400">Please check your network status or API key validity.</p>
                        </div>
                    </div>
                </div>
            )}

            {generatedImageUrl && (
                <div className="flex flex-col items-center gap-6 mt-2">

                    {/* Artwork */}
                    <div className="neo-box overflow-hidden w-full shadow-xl">
                        <div className="p-3 bg-white border-2 border-gray-100">
                            <img src={generatedImageUrl} alt="AI Generated Code Art" className="w-full h-auto block" />
                        </div>
                        <div className="text-center text-xs text-gray-400 py-2 bg-gray-50 border-t border-gray-100 uppercase tracking-widest font-bold">
                            {resolvedStyleInfo.artist} · {resolvedStyleInfo.movement[locale]}
                        </div>
                    </div>

                    {/* Docent */}
                    <div className="w-full bg-[#fdfbf7] p-5 border-l-4 border-secondary neo-box-sm shadow-sm">
                        <div className="flex items-center gap-2 mb-3">
                            <span className="text-xl">🧐</span>
                            <h4 className="font-bold text-base text-gray-800">{t('result.docent')}</h4>
                            {isGeneratingDocent && (
                                <span className="ml-auto flex items-center gap-1 text-xs text-gray-400">
                                    <RefreshCw className="animate-spin" size={12} /> {t('result.docent.loading')}
                                </span>
                            )}
                        </div>
                        {isGeneratingDocent ? (
                            <div className="h-16 bg-gray-100 rounded animate-pulse" />
                        ) : docentText ? (
                            <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">{docentText}</p>
                        ) : docentError ? (
                            <p className="text-xs text-red-400 italic">{docentError}</p>
                        ) : (
                            <p className="text-sm text-gray-400 italic">{t('result.docent.error')}</p>
                        )}
                    </div>

                    {/* Actions */}
                    <div className="flex gap-3 w-full justify-center">
                        <button
                            onClick={downloadImage}
                            className="neo-box-sm bg-white px-4 py-2 text-sm font-bold flex items-center gap-2 hover:bg-gray-50"
                        >
                            <Download size={15} /> {t('result.download')}
                        </button>
                        <button
                            onClick={() => { setGeneratedImageUrl(null); setDocentText(null); }}
                            className="neo-box-sm bg-gray-100 px-4 py-2 text-sm font-bold hover:bg-gray-200"
                        >
                            {t('result.retry')}
                        </button>
                    </div>

                    {/* Collapsible Details */}
                    <details className="w-full group">
                        <summary className="cursor-pointer text-xs font-bold text-gray-400 uppercase tracking-wide flex items-center gap-2 select-none hover:text-gray-600 transition-colors">
                            <span>▸ {t('result.details')}</span>
                        </summary>
                        <div className="mt-3 flex flex-col gap-3">
                            <div className="flex flex-col md:flex-row gap-3">
                                <select
                                    value={aiProvider}
                                    onChange={(e) => setAiProvider(e.target.value as 'openai' | 'gemini')}
                                    className="neo-box-sm px-3 py-2 text-sm bg-white flex-grow"
                                >
                                    {hasGemini && <option value="gemini">{t('editor.model.gemini')}</option>}
                                    {hasOpenAI && <option value="openai">{t('editor.model.openai')}</option>}
                                </select>
                                <button
                                    onClick={handleGenerate}
                                    disabled={isGenerating}
                                    className="neo-box-sm bg-secondary text-white font-bold px-4 py-2 flex items-center gap-2 text-sm hover:bg-[#ffafa0] disabled:opacity-50"
                                >
                                    {isGenerating ? <RefreshCw className="animate-spin" size={14} /> : null}
                                    {t('result.regenerate')}
                                </button>
                            </div>
                            <div>
                                <label className="text-xs font-bold text-gray-400 uppercase mb-1 block">{t('result.prompt')}</label>
                                <textarea
                                    readOnly
                                    value={currentPrompt}
                                    className="w-full h-36 p-3 bg-gray-50 border border-gray-200 text-xs text-gray-600 resize-none font-mono rounded"
                                />
                            </div>
                        </div>
                    </details>
                </div>
            )}
        </div>
    );
}
